# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/esme/Desktop/VivadoProjects/U20U96/U20U96.srcs/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_ds_6/u96v2_sbc_base_auto_ds_6.xci
# IP: The module: 'u96v2_sbc_base_auto_ds_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/esme/Desktop/VivadoProjects/U20U96/U20U96.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_ds_6/u96v2_sbc_base_auto_ds_6_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_auto_ds_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/esme/Desktop/VivadoProjects/U20U96/U20U96.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_ds_6/u96v2_sbc_base_auto_ds_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_auto_ds_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/esme/Desktop/VivadoProjects/U20U96/U20U96.srcs/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_ds_6/u96v2_sbc_base_auto_ds_6.xci
# IP: The module: 'u96v2_sbc_base_auto_ds_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/esme/Desktop/VivadoProjects/U20U96/U20U96.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_ds_6/u96v2_sbc_base_auto_ds_6_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_auto_ds_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/esme/Desktop/VivadoProjects/U20U96/U20U96.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_ds_6/u96v2_sbc_base_auto_ds_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_auto_ds_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
